title: Internet Archive Export Tool
description: This add-on allows you to select documents from DocumentCloud and upload all the documents to the Internet Archive for archiving.
instructions: |
 This DocumentCloud Add-On allows you to backup documents from DocumentCloud to DocumentCloud's Internet Archive (archive.org) account and optionally the IPFS/Filecoin networks. See our [Internet Archive page](https://archive.org/details/@documentcloudupload) for all documents currently backed up on archive.org
 If you fork this project, you can set your own repository secrets, name them IA_USER (your internet archive username) and IA_PASS (your internet archive password) which will allow you to backup your projects to your own Internet Archive account.
 This Add-On was developed using the [Internet Archive's Python Library](https://archive.org/services/docs/api/internetarchive/). 
disclosures: |
 This Add-On uploads documents to the Internet Archive. By default, this will upload documents to DocumentCloud's Internet Archive account which is public unless you fork this Add-On and use your own credentials.
 Read the Internet Archive's [privacy policy](https://archive.org/about/terms) to learn more. 
type: object
properties:
 to_tag:
  title: Tag Documents
  type: boolean
  default: true
  description: This will tag documents uploaded to the archive successfully with a key 'ia_url' that contains a link to the item on the Internet Archive. 
 filecoin:
    title: Push to IPFS/Filecoin
    type: boolean
    description: >-
      WARNING: This will push all scraped files to IPFS and Filecoin.  
      There is no way to remove files from these storage systems.
documents:
 - selected
categories:
 - export
