title: Internet Archive Export Tool
description: This add-on allows you to select a project from DocumentCloud and upload all the documents to the Internet Archive for archiving.
type: object
properties:
  pname:
    title: Name of DocumentCloud project you would like archived. 
    type: string
  iname: 
    title: Name of Internet Archive item (basically their version of projects) that you would like the documents uploaded to. Spaces are not an allowed character for item names and will be replaced with dashes. 
    type: string
required:
    -pname
    -iname
