title: Internet Archive Export Tool
description: This add-on allows you to select a project from DocumentCloud and upload all the documents to the Internet Archive for archiving.
type: object
documents:
 -query
 -selected
properties:
 item_name: 
  title: Name of Internet Archive item
  type: string
required:
 - itemname
