title: Internet Archive Export Tool
description: This add-on allows you to select documents from DocumentCloud and upload all the documents to the Internet Archive for archiving.
instructions: |
 This DocumentCloud Add-On allows you to backup documents from DocumentCloud to DocumentCloud's Internet Archive (archive.org) account. See our [Internet Archive page](https://archive.org/details/@documentcloudupload) for all documents currently backed up on archive.org
 If you fork this project, you can set your own repository secrets, name them IA_USER (your internet archive username) and IA_PASS (your internet archive password) which will allow you to backup your projects to your own Internet Archive account.
 This Add-On was developed using the [Internet Archive's Python Library](https://archive.org/services/docs/api/internetarchive/). 
type: object
properties:
 item_name: 
  title: Name of Internet Archive item
  type: string
required:
 - item_name
documents:
 - query
 - selected
categories:
 - export
